### ISSUE TITLE
Rust panics 

### ISSUE THREAD

**Issue by Rippanda12** [heyitzspencer/optichime#1]
`[panda@Panda optichime]$ cargo run /home/rippanda12/Instances/New Folder1/.minecraft/resourcepacks/Far block v0.7/
  Downloaded serde_json v1.0.64
  Downloaded itoa v0.4.7
  Downloaded serde v1.0.124
  Downloaded 3 crates (201.7 KB) in 0.88s
   Compiling ryu v1.0.5
   Compiling serde v1.0.124
   Compiling serde_json v1.0.64
   Compiling itoa v0.4.7
   Compiling same-file v1.0.6
   Compiling walkdir v2.3.1
   Compiling optichime v0.1.0 (/home/panda/optichime)
    Finished dev [unoptimized + debuginfo] target(s) in 20.14s
     Running `target/debug/optichime /home/rippanda12/Instances/New Folder1/.minecraft/resourcepacks/Far block v0.7/`
thread 'main' panicked at 'Error reading Optifine Pack Path: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:38:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

**Comment by Rippanda12** [comment]
Removing spaces in folders got it to go somewhere but it still dosent complete still panics
`thread 'main' panicked at 'Property could not be registered', src/main.rs:173:94
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

**Comment by Icelk** [comment]
Does the problem still persist in the latest commit?

**Comment by LaytonGB** [comment]
> Does the problem still persist in the latest commit?

Yes, same problem here.

`thread 'main' panicked at 'Property could not be registered', src\main.rs:186:88` when used on https://www.mediafire.com/file/rd3ro5wyizw4fc2/Mizuno%2527s_16_Craft_JE_1.18.2-1.0.zip/file
